#!/usr/bin/env python3
"""Bundle a compiled LaTeX project into an arXiv-ready tarball.

Reads the .fls file latexmk produces (`-recorder`), which lists every file the build
actually opened. That is the authoritative dependency list: unused figures, old drafts,
and editor scratch files are excluded automatically because TeX never read them.

Usage:
    make_arxiv.py --main main_arxiv.tex --out dist/paper-arxiv.tar.gz
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import sys
import tarfile
import tempfile

# Build products. These are regenerated by arXiv's TeX run, except .bbl which arXiv
# requires because it does not run BibTeX.
GENERATED_SUFFIXES = {
    ".aux", ".log", ".out", ".fls", ".fdb_latexmk", ".synctex.gz", ".toc", ".lof",
    ".lot", ".nav", ".snm", ".brf", ".blg", ".run.xml", ".bcf", ".xdv", ".dvi",
}

VERBATIM_BEGIN = re.compile(r"\\begin\{(verbatim|lstlisting|minted|Verbatim|alltt)\*?\}")
VERBATIM_END = re.compile(r"\\end\{(verbatim|lstlisting|minted|Verbatim|alltt)\*?\}")


def strip_comments(text: str) -> str:
    """Blank out comment bodies while keeping the '%' itself.

    Keeping the '%' matters: a trailing '%' suppresses the newline's inter-word space,
    so deleting the whole line would silently change spacing. Verbatim-like
    environments are left untouched.
    """
    out = []
    in_verbatim = False
    for line in text.split("\n"):
        if in_verbatim:
            out.append(line)
            if VERBATIM_END.search(line):
                in_verbatim = False
            continue
        if VERBATIM_BEGIN.search(line):
            in_verbatim = True
            out.append(line)
            continue

        result, i = [], 0
        while i < len(line):
            char = line[i]
            if char == "\\" and i + 1 < len(line):
                result.append(line[i : i + 2])
                i += 2
                continue
            if char == "%":
                result.append("%")
                break
            result.append(char)
            i += 1
        out.append("".join(result))
    return "\n".join(out)


def fls_inputs(fls_path: str, root: str) -> list[str]:
    """Absolute paths of project-local files the build read, in first-seen order."""
    seen, ordered = set(), []
    cwd = root
    with open(fls_path, encoding="utf-8", errors="replace") as fh:
        for line in fh:
            if line.startswith("PWD "):
                cwd = line[4:].strip()
            elif line.startswith("INPUT "):
                raw = line[6:].strip()
                path = os.path.normpath(raw if os.path.isabs(raw) else os.path.join(cwd, raw))
                if not os.path.isfile(path):
                    continue
                real = os.path.realpath(path)
                # Anything outside the project tree is a TeX Live system file; arXiv
                # supplies its own, so shipping ours would be wrong as well as large.
                if os.path.commonpath([real, os.path.realpath(root)]) != os.path.realpath(root):
                    continue
                if real not in seen:
                    seen.add(real)
                    ordered.append(real)
    return ordered


def is_generated(path: str, keep: set[str]) -> bool:
    name = os.path.basename(path)
    if name in keep:
        return False
    for suffix in GENERATED_SUFFIXES:
        if name.endswith(suffix):
            return True
    return False


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--main", required=True, help="main .tex file that was compiled")
    parser.add_argument("--out", required=True, help="tarball to write (.tar.gz)")
    parser.add_argument("--root", default=".", help="project root (default: cwd)")
    parser.add_argument("--include-bib", action="store_true",
                        help="ship .bib files too (arXiv does not need them when a .bbl is present)")
    parser.add_argument("--keep-comments", action="store_true",
                        help="do not strip LaTeX comments from shipped sources")
    args = parser.parse_args()

    root = os.path.realpath(args.root)
    stem = os.path.splitext(os.path.basename(args.main))[0]
    fls = os.path.join(root, stem + ".fls")
    bbl = os.path.join(root, stem + ".bbl")

    if not os.path.isfile(fls):
        print(f"make_arxiv: no {stem}.fls -- build with 'latexmk -recorder' first", file=sys.stderr)
        return 1

    inputs = fls_inputs(fls, root)
    keep = {stem + ".bbl"}
    files = [p for p in inputs if not is_generated(p, keep)]

    if not args.include_bib:
        files = [p for p in files if not p.endswith(".bib")]

    # The .bbl is read only when it exists at build time; on a clean checkout latexmk
    # generates it mid-run, so the .fls may not list it. Add it explicitly.
    if os.path.isfile(bbl) and os.path.realpath(bbl) not in files:
        files.append(os.path.realpath(bbl))
    elif not os.path.isfile(bbl):
        print(f"make_arxiv: WARNING {stem}.bbl missing -- arXiv will not run BibTeX, "
              "so the submission will have no bibliography", file=sys.stderr)

    main_real = os.path.realpath(os.path.join(root, args.main))
    if main_real not in files:
        files.insert(0, main_real)

    os.makedirs(os.path.dirname(os.path.abspath(args.out)) or ".", exist_ok=True)

    with tempfile.TemporaryDirectory() as staging:
        total = 0
        for src in files:
            rel = os.path.relpath(src, root)
            # arXiv resolves \usepackage/\documentclass/\bibliographystyle through
            # TEXINPUTS, which covers only the top level -- a local vendor/ directory
            # that works here would break there. Figures and \input'd body files are
            # referenced by explicit path, so those keep their layout.
            if rel.endswith((".sty", ".cls", ".bst")):
                rel = os.path.basename(rel)
            dst = os.path.join(staging, rel)
            os.makedirs(os.path.dirname(dst), exist_ok=True)
            if src.endswith((".tex", ".sty", ".cls")) and not args.keep_comments:
                with open(src, encoding="utf-8", errors="replace") as fh:
                    text = fh.read()
                with open(dst, "w", encoding="utf-8") as fh:
                    fh.write(strip_comments(text))
            else:
                shutil.copy2(src, dst)
            total += os.path.getsize(dst)
            print(f"  + {rel}")

        with tarfile.open(args.out, "w:gz") as tar:
            for entry in sorted(os.listdir(staging)):
                tar.add(os.path.join(staging, entry), arcname=entry)

    size_mb = os.path.getsize(args.out) / 1e6
    print(f"make_arxiv: {len(files)} files, {total/1e6:.1f} MB raw -> {args.out} ({size_mb:.1f} MB)")
    if size_mb > 50:
        print("make_arxiv: WARNING tarball exceeds arXiv's 50 MB limit", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
