#!/usr/bin/env python3
"""Emit a BibTeX file containing only the entries a document actually cites.

The shared bibliography holds hundreds of entries; a paper cites a few dozen. arXiv
submissions should carry only what they use, so this reads the .aux file(s) produced by
a LaTeX run and writes a pruned .bib.

Usage:
    prune_bib.py --aux main.aux --bib bib/refs.bib --out refs.bib
"""

from __future__ import annotations

import argparse
import re
import sys

CITATION_RE = re.compile(r"\\(?:citation|abx@aux@cite(?:\{[^}]*\})?)\{([^}]*)\}")
ENTRY_START_RE = re.compile(r"@(\w+)\s*[{(]\s*([^,\s]*)\s*,", re.IGNORECASE)
CROSSREF_RE = re.compile(r"\bcrossref\s*=\s*[{\"]([^}\"]+)[}\"]", re.IGNORECASE)

# Entry types that carry no citation key and must always be kept.
PREAMBLE_TYPES = {"string", "preamble"}


def cited_keys(aux_paths: list[str]) -> tuple[set[str], bool]:
    """Return (keys, cite_all) from the given .aux files."""
    keys: set[str] = set()
    cite_all = False
    for path in aux_paths:
        with open(path, encoding="utf-8", errors="replace") as fh:
            text = fh.read()
        for group in CITATION_RE.findall(text):
            for key in group.split(","):
                key = key.strip()
                if key == "*":
                    cite_all = True
                elif key:
                    keys.add(key)
    return keys, cite_all


def parse_entries(text: str) -> list[tuple[str, str, str]]:
    """Split a .bib file into (type, key, raw_text) tuples via brace matching."""
    entries = []
    pos = 0
    while True:
        match = ENTRY_START_RE.search(text, pos)
        if not match:
            break
        start = match.start()

        # @string/@preamble have no key, so ENTRY_START_RE may have mis-parsed them;
        # re-detect the type directly and scan from the opening delimiter.
        type_match = re.match(r"@(\w+)", text[start:])
        etype = type_match.group(1).lower() if type_match else ""

        open_idx = text.find("{", start)
        paren_idx = text.find("(", start)
        if open_idx == -1 or (paren_idx != -1 and paren_idx < open_idx):
            open_idx, opener, closer = paren_idx, "(", ")"
        else:
            opener, closer = "{", "}"
        if open_idx == -1:
            break

        depth, i = 0, open_idx
        in_quote = False
        while i < len(text):
            char = text[i]
            if char == "\\":
                i += 2
                continue
            if char == '"' and depth == 1:
                in_quote = not in_quote
            elif not in_quote:
                if char == opener:
                    depth += 1
                elif char == closer:
                    depth -= 1
                    if depth == 0:
                        break
            i += 1

        end = min(i + 1, len(text))
        entries.append((etype, match.group(2).strip(), text[start:end]))
        pos = end
    return entries


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--aux", action="append", required=True, help="LaTeX .aux file (repeatable)")
    parser.add_argument("--bib", action="append", required=True, help="source .bib file (repeatable)")
    parser.add_argument("--out", required=True, help="pruned .bib to write")
    args = parser.parse_args()

    wanted, cite_all = cited_keys(args.aux)

    all_entries: list[tuple[str, str, str]] = []
    for path in args.bib:
        with open(path, encoding="utf-8", errors="replace") as fh:
            all_entries.extend(parse_entries(fh.read()))

    by_key = {key.lower(): (etype, key, raw) for etype, key, raw in all_entries if etype not in PREAMBLE_TYPES}

    if cite_all:
        selected = set(by_key)
    else:
        # Follow crossref chains so inherited fields survive the prune.
        selected, queue = set(), [k.lower() for k in wanted]
        while queue:
            key = queue.pop()
            if key in selected or key not in by_key:
                continue
            selected.add(key)
            queue.extend(ref.lower() for ref in CROSSREF_RE.findall(by_key[key][2]))

    missing = sorted(k for k in {w.lower() for w in wanted} if k not in by_key)
    if missing:
        print(f"prune_bib: WARNING {len(missing)} cited key(s) not in bibliography:", file=sys.stderr)
        for key in missing:
            print(f"  - {key}", file=sys.stderr)

    with open(args.out, "w", encoding="utf-8") as out:
        out.write("% Generated by prune_bib.py -- do not edit.\n")
        out.write("% Pruned from: " + ", ".join(args.bib) + "\n\n")
        for etype, _key, raw in all_entries:
            if etype in PREAMBLE_TYPES:
                out.write(raw + "\n\n")
        written = set()
        for etype, key, raw in all_entries:
            if etype in PREAMBLE_TYPES:
                continue
            low = key.lower()
            if low in selected and low not in written:
                written.add(low)
                out.write(raw + "\n\n")

    print(f"prune_bib: {len(written)} of {len(by_key)} entries kept -> {args.out}")
    return 1 if missing else 0


if __name__ == "__main__":
    sys.exit(main())
